# Generated by Django 4.1.2 on 2022-10-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_certificatedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatedetail',
            name='cert_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
